version: "3.7"
services:

    # volumes sind überall auskommentiert, falls das Filesystem oder Docker
    # Volumes zur Persistenz verwendet werden sollen entsprechend einkommentieren

    # MySQL Container
    db_mysql:
        image: mysql:5.7
        ports:
            - 3306:3306
        restart: always
        environment:
            MYSQL_DATABASE: testapp
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_RANDOM_ROOT_PASSWORD: '1'
        #volumes:
            #- ./docker/mysql:/var/lib/mysql
        networks:
            - spring-cloud-network

    # DB Administration (optional)
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8181:8181
        environment:
            PMA_HOST: db_mysql
            MYSQL_USERNAME: user
            MYSQL_ROOT_PASSWORD: password
        networks:
            - spring-cloud-network
        depends_on: 
            - db_mysql

    rabbitmq:
        image: 127.0.0.1:5000/vs-rmq
        build:
            context: ./
            dockerfile: docker/rabbitmq/Dockerfile
        ports:
            - 61613:61613           
        #volumes:
            #- ./docker/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
        networks:
            - spring-cloud-network

networks:
    spring-cloud-network:
        driver: overlay