/* eslint-disable */
/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Board from './Board';
import User from './User';

/**
* The Group model module.
* @module model/Group
* @version 1.0
*/
export default class Group {
    /**
    * Constructs a new <code>Group</code>.
    * @alias module:model/Group
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>Group</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Group} obj Optional instance to populate.
    * @return {module:model/Group} The populated <code>Group</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Group();
                        
            
            if (data.hasOwnProperty('board')) {
                obj['board'] = Board.constructFromObject(data['board']);
            }
            if (data.hasOwnProperty('coordinator')) {
                obj['coordinator'] = User.constructFromObject(data['coordinator']);
            }
            if (data.hasOwnProperty('groupName')) {
                obj['groupName'] = ApiClient.convertToType(data['groupName'], 'String');
            }
            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Board} board
    */
    'board' = undefined;
    /**
    * @member {module:model/User} coordinator
    */
    'coordinator' = undefined;
    /**
    * @member {String} groupName
    */
    'groupName' = undefined;
    /**
    * @member {Number} id
    */
    'id' = undefined;




}
