/* eslint-disable */

/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The View model module.
* @module model/View
* @version 1.0
*/
export default class View {
    /**
    * Constructs a new <code>View</code>.
    * @alias module:model/View
    * @class
    */

    constructor() {
        
        
        
    }

    /**
    * Constructs a <code>View</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/View} obj Optional instance to populate.
    * @return {module:model/View} The populated <code>View</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new View();
                        
            
            if (data.hasOwnProperty('contentType')) {
                obj['contentType'] = ApiClient.convertToType(data['contentType'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} contentType
    */
    'contentType' = undefined;




}
