/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.BoardsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BoardsApi', function() {
    describe('addBoardUsingPOST', function() {
      it('should call addBoardUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addBoardUsingPOST
        //instance.addBoardUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteBoardUsingDELETE', function() {
      it('should call deleteBoardUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteBoardUsingDELETE
        //instance.deleteBoardUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardUsingGET', function() {
      it('should call getBoardUsingGET successfully', function(done) {
        //uncomment below and update the code to test getBoardUsingGET
        //instance.getBoardUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getBoardsUsingGET', function() {
      it('should call getBoardsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getBoardsUsingGET
        //instance.getBoardsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceBoardUsingPOST', function() {
      it('should call replaceBoardUsingPOST successfully', function(done) {
        //uncomment below and update the code to test replaceBoardUsingPOST
        //instance.replaceBoardUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
