/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.GroupsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GroupsApi', function() {
    describe('addGroupUsingPOST', function() {
      it('should call addGroupUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addGroupUsingPOST
        //instance.addGroupUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('addUserToGroupUsingPOST', function() {
      it('should call addUserToGroupUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addUserToGroupUsingPOST
        //instance.addUserToGroupUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeCoordinatorUsingPOST', function() {
      it('should call changeCoordinatorUsingPOST successfully', function(done) {
        //uncomment below and update the code to test changeCoordinatorUsingPOST
        //instance.changeCoordinatorUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteGroupUsingDELETE', function() {
      it('should call deleteGroupUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteGroupUsingDELETE
        //instance.deleteGroupUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGroupUsingGET', function() {
      it('should call getGroupUsingGET successfully', function(done) {
        //uncomment below and update the code to test getGroupUsingGET
        //instance.getGroupUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getGroupsUsingGET', function() {
      it('should call getGroupsUsingGET successfully', function(done) {
        //uncomment below and update the code to test getGroupsUsingGET
        //instance.getGroupsUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
