/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ApiDocumentation);
  }
}(this, function(expect, ApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ApiDocumentation.UsersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UsersApi', function() {
    describe('addUserUsingPOST', function() {
      it('should call addUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test addUserUsingPOST
        //instance.addUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeOwnPasswordUsingPOST', function() {
      it('should call changeOwnPasswordUsingPOST successfully', function(done) {
        //uncomment below and update the code to test changeOwnPasswordUsingPOST
        //instance.changeOwnPasswordUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('changeSomeonesPasswordUsingPOST', function() {
      it('should call changeSomeonesPasswordUsingPOST successfully', function(done) {
        //uncomment below and update the code to test changeSomeonesPasswordUsingPOST
        //instance.changeSomeonesPasswordUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUserUsingDELETE', function() {
      it('should call deleteUserUsingDELETE successfully', function(done) {
        //uncomment below and update the code to test deleteUserUsingDELETE
        //instance.deleteUserUsingDELETE(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUserUsingGET', function() {
      it('should call getUserUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUserUsingGET
        //instance.getUserUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getUsersUsingGET', function() {
      it('should call getUsersUsingGET successfully', function(done) {
        //uncomment below and update the code to test getUsersUsingGET
        //instance.getUsersUsingGET(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('replaceUserUsingPOST', function() {
      it('should call replaceUserUsingPOST successfully', function(done) {
        //uncomment below and update the code to test replaceUserUsingPOST
        //instance.replaceUserUsingPOST(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
